% this script will change the names of all the .SER files (run files),
% according to the order indicated in the serdes.txt files

clear all; clc;

cd /Volumes/y/cfmi_data/csl_pract

subj = dir('*');
n_subj = length(subj) - 4; % dir command pulls ncecessary folders (minus 4 unnecessary)
for h = 1:n_subj;
    g = subj(h+4).name; % same reasoning as above
    eval(sprintf('cd ./%s/;',g));
    sess = dir('*.STU');
    n_sess = length(sess);
    
    for i = 1:n_sess
    t = sess(i).name;
        eval(sprintf('cd ./%s/;',t));
        

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Volumes/y/cfmi_data/csl_data/13.h.12/1.3.12.2.1107.5.2.32.35052.30000010102221451332800000034.STU/serdes.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/09/15 13:21:28

%% Initialize variables.
filename = [pwd '/serdes.txt'];
delimiter = '\t';

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
% VarName1 = dataArray{:, 1};
% VarName2 = dataArray{:, 2};


%% Rename SERs
SERs = dir('*.SER');
n_SER = length(SERs); 
           for ii = 1:n_SER
           % s = SERs(ii).name;
                c = 0;
                for iii = 1:n_SER
                    if strcmp(SERs(ii).name,dataArray{:,2}{iii})
                        if strcmp(dataArray{:,1}{iii},'MoCoSeries');
                            c = c + 1;
                            movefile(SERs(ii).name,[dataArray{:,1}{iii} c]);
                        else
                            movefile(SERs(ii).name,dataArray{:,1}{iii});
                        end
                    end
                end
           end
    
   
clearvars filename delimiter formatSpec fileID dataArray ans;

           cd ../

    end
    cd ../
end